name: Keep Render Backend Awake

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl backend health endpoint
        run: |
          echo "Pinging backend at $(date)..."

          for i in 1 2 3; do
            RESPONSE=$(curl -s -o - -w "%{http_code}" --fail https://zomato-chatbot-backend.onrender.com/chatbot/health 2>/dev/null || echo "000")
            STATUS=${RESPONSE: -3}
            BODY=${RESPONSE::-3}

            echo "Attempt $i - HTTP code: $STATUS"

            if [ "$STATUS" -eq 200 ]; then
              echo "Backend is alive!"
              echo "Response body:"
              echo "$BODY"
              exit 0
            fi

            if [ "$i" -lt 3 ]; then
              echo "Attempt $i failed, retrying in 10s..."
              sleep 10
            fi
          done

          echo "Backend did not respond successfully after 3 attempts."
          echo "Last response body:"
          echo "$BODY"
          exit 1
