name: Keep Render Backend Awake

on:
  schedule:
    - cron: "*/10 * * * *"  # every 5 minutes
  workflow_dispatch:       # allows manual run from GitHub Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl backend health endpoint
        run: |
          echo "Pinging backend at $(date)..."
          RESPONSE=$(curl -s -w "%{http_code}" -o response.json https://zomato-chatbot-backend.onrender.com/chatbot/health)
          echo "HTTP code: $RESPONSE"

          if [ "$RESPONSE" -eq 200 ]; then
            echo "Backend is alive!"
            echo "Response body:"
            cat response.json
          else
            echo "Backend did not return 200. Something may be wrong."
            echo "Response body (if any):"
            cat response.json
            exit 1
          fi
